version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_hackathon_prep
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hackathon_prep
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
